from enum import Enum


class ErrorCode(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Domain examples:
    USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_REFRESH_REVOKED = "AUTH_REFRESH_REVOKED"
    AUTH_REFRESH_EXPIRED = "AUTH_REFRESH_EXPIRED"
    AUTH_REFRESH_INVALID = "AUTH_REFRESH_INVALID"