"""add RAG policy, context, and retrieval log tables

Revision ID: 0f8e0583c04e
Revises: e55696bc319c
Create Date: 2026-02-28 22:14:13.060444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = "0f8e0583c04e"
down_revision: Union[str, Sequence[str], None] = "e55696bc319c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_terms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("term", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("window_1", sa.Integer(), nullable=False),
        sa.Column("window_2", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_terms_company_id"),
        "context_terms",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_terms_entity_type"),
        "context_terms",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_terms_lang"), "context_terms", ["lang"], unique=False
    )
    op.create_index(
        op.f("ix_context_terms_term"), "context_terms", ["term"], unique=False
    )
    op.create_table(
        "policy_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("doc_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_policy_documents_company_enabled",
        "policy_documents",
        ["company_id", "enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_documents_company_id"),
        "policy_documents",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_documents_created_by"),
        "policy_documents",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_documents_doc_type"),
        "policy_documents",
        ["doc_type"],
        unique=False,
    )
    op.create_table(
        "context_term_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("context_term_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["context_term_id"],
            ["context_terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "context_term_id", "model_name", name="uq_context_term_embedding_model"
        ),
    )
    op.create_index(
        op.f("ix_context_term_embeddings_context_term_id"),
        "context_term_embeddings",
        ["context_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_term_embeddings_model_name"),
        "context_term_embeddings",
        ["model_name"],
        unique=False,
    )
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["policy_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_policy_chunk_order"),
    )
    op.create_index(
        op.f("ix_policy_chunks_chunk_index"),
        "policy_chunks",
        ["chunk_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_chunks_company_id"),
        "policy_chunks",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_chunks_content_hash"),
        "policy_chunks",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_chunks_document_id"),
        "policy_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "policy_chunk_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["policy_chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chunk_id", "model_name", name="uq_policy_chunk_embedding_model"
        ),
    )
    op.create_index(
        op.f("ix_policy_chunk_embeddings_chunk_id"),
        "policy_chunk_embeddings",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_chunk_embeddings_model_name"),
        "policy_chunk_embeddings",
        ["model_name"],
        unique=False,
    )
    op.create_table(
        "rag_retrieval_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column(
            "results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_retrieval_logs_message_id"),
        "rag_retrieval_logs",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rag_retrieval_logs_message_id"), table_name="rag_retrieval_logs"
    )
    op.drop_table("rag_retrieval_logs")
    op.drop_index(
        op.f("ix_policy_chunk_embeddings_model_name"),
        table_name="policy_chunk_embeddings",
    )
    op.drop_index(
        op.f("ix_policy_chunk_embeddings_chunk_id"),
        table_name="policy_chunk_embeddings",
    )
    op.drop_table("policy_chunk_embeddings")
    op.drop_index(op.f("ix_policy_chunks_document_id"), table_name="policy_chunks")
    op.drop_index(op.f("ix_policy_chunks_content_hash"), table_name="policy_chunks")
    op.drop_index(op.f("ix_policy_chunks_company_id"), table_name="policy_chunks")
    op.drop_index(op.f("ix_policy_chunks_chunk_index"), table_name="policy_chunks")
    op.drop_table("policy_chunks")
    op.drop_index(
        op.f("ix_context_term_embeddings_model_name"),
        table_name="context_term_embeddings",
    )
    op.drop_index(
        op.f("ix_context_term_embeddings_context_term_id"),
        table_name="context_term_embeddings",
    )
    op.drop_table("context_term_embeddings")
    op.drop_index(op.f("ix_policy_documents_doc_type"), table_name="policy_documents")
    op.drop_index(op.f("ix_policy_documents_created_by"), table_name="policy_documents")
    op.drop_index(op.f("ix_policy_documents_company_id"), table_name="policy_documents")
    op.drop_index("ix_policy_documents_company_enabled", table_name="policy_documents")
    op.drop_table("policy_documents")
    op.drop_index(op.f("ix_context_terms_term"), table_name="context_terms")
    op.drop_index(op.f("ix_context_terms_lang"), table_name="context_terms")
    op.drop_index(op.f("ix_context_terms_entity_type"), table_name="context_terms")
    op.drop_index(op.f("ix_context_terms_company_id"), table_name="context_terms")
    op.drop_table("context_terms")
    # ### end Alembic commands ###
