"""add column stable_key NOT NULL

Revision ID: 9850b0698762
Revises: 4618bd02912b
Create Date: 2026-02-22 21:43:13.906148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9850b0698762"
down_revision: Union[str, Sequence[str], None] = "4618bd02912b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column("stable_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(op.f("ix_rules_stable_key"), "rules", ["stable_key"], unique=False)
    op.create_index(
        "ix_rules_stable_key_company",
        "rules",
        ["stable_key", "company_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rules_stable_key_company", table_name="rules")
    op.drop_index(op.f("ix_rules_stable_key"), table_name="rules")
    op.drop_column("rules", "stable_key")
    # ### end Alembic commands ###
