"""init tables

Revision ID: b98fe549bb47
Revises:
Create Date: 2026-02-20 00:46:59.336353

"""

from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "b98fe549bb47"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="company_status"),
            server_default="active",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix_companies_status"), "companies", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="user_status"),
            server_default="active",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "company_members",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "company_admin", name="member_role"),
            server_default="member",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "removed", name="member_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "company_id", name="uq_company_members_user_company"
        ),
    )
    op.create_index(
        "ix_company_members_company_role_status",
        "company_members",
        ["company_id", "role", "status"],
        unique=False,
    )
    op.create_index(
        "ix_company_members_company_status",
        "company_members",
        ["company_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_company_members_user_status",
        "company_members",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="conversation_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("last_sequence_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversations_company_user",
        "conversations",
        ["company_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_status"), "conversations", ["status"], unique=False
    )
    op.create_index(
        "ix_conversations_user_created",
        "conversations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "rules",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("prompt", "chat", "file", "api", name="rule_scope"),
            nullable=False,
        ),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "conditions_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "action",
            sa.Enum("allow", "mask", "block", "warn", name="rule_action"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", name="rule_severity"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "rag_mode",
            sa.Enum("off", "explain", "verify", name="rag_mode"),
            server_default="off",
            nullable=False,
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rules_company_enabled_scope",
        "rules",
        ["company_id", "enabled", "scope"],
        unique=False,
    )
    op.create_index(
        "ix_rules_company_enabled_scope_priority",
        "rules",
        ["company_id", "enabled", "scope", "priority"],
        unique=False,
    )
    op.create_index(op.f("ix_rules_enabled"), "rules", ["enabled"], unique=False)
    op.create_index(
        "ix_rules_enabled_scope", "rules", ["enabled", "scope"], unique=False
    )
    op.create_index(op.f("ix_rules_name"), "rules", ["name"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("system", "user", "assistant", name="message_role"),
            nullable=False,
        ),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "input_type",
            sa.Enum(
                "user_input", "system_prompt", "tool_result", name="message_input_type"
            ),
            server_default="user_input",
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("content_masked", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "scan_status",
            sa.Enum("pending", "done", "failed", name="scan_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("scan_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "pre_rag_action",
            sa.Enum("allow", "mask", "block", "warn", name="rule_action"),
            nullable=True,
        ),
        sa.Column(
            "final_action",
            sa.Enum("allow", "mask", "block", "warn", name="rule_action"),
            nullable=True,
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column(
            "ambiguous", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "matched_rule_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "entities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "rag_evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "sequence_number", name="uq_messages_convo_seq"
        ),
    )
    op.create_index(
        "ix_messages_content_hash", "messages", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_final_action", "messages", ["final_action"], unique=False
    )
    op.create_index(
        "ix_messages_scan_status", "messages", ["scan_status"], unique=False
    )
    op.create_table(
        "rule_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rule_id", "model_name", name="uq_rule_embeddings_rule_model"
        ),
    )
    op.create_index(
        op.f("ix_rule_embeddings_content_hash"),
        "rule_embeddings",
        ["content_hash"],
        unique=True,
    )
    op.create_table(
        "prompt_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("regex", "presidio", "llm", name="entity_source"),
            nullable=False,
        ),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_index", sa.Integer(), nullable=True),
        sa.Column("end_index", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("text_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prompt_entities_message", "prompt_entities", ["message_id"], unique=False
    )
    op.create_index(
        "ix_prompt_entities_type", "prompt_entities", ["entity_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompt_entities_type", table_name="prompt_entities")
    op.drop_index("ix_prompt_entities_message", table_name="prompt_entities")
    op.drop_table("prompt_entities")
    op.drop_index(op.f("ix_rule_embeddings_content_hash"), table_name="rule_embeddings")
    op.drop_table("rule_embeddings")
    op.drop_index("ix_messages_scan_status", table_name="messages")
    op.drop_index("ix_messages_final_action", table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_index("ix_messages_content_hash", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_rules_name"), table_name="rules")
    op.drop_index("ix_rules_enabled_scope", table_name="rules")
    op.drop_index(op.f("ix_rules_enabled"), table_name="rules")
    op.drop_index("ix_rules_company_enabled_scope_priority", table_name="rules")
    op.drop_index("ix_rules_company_enabled_scope", table_name="rules")
    op.drop_table("rules")
    op.drop_index("ix_conversations_user_created", table_name="conversations")
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_index("ix_conversations_company_user", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_company_members_user_status", table_name="company_members")
    op.drop_index("ix_company_members_company_status", table_name="company_members")
    op.drop_index(
        "ix_company_members_company_role_status", table_name="company_members"
    )
    op.drop_table("company_members")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_companies_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
